---
kind: Namespace
apiVersion: v1
metadata:
  name: brobot
  labels:
    name: brobot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brobot
  namespace: brobot
  labels:
    app.kubernetes.io/name: brobot
    app.kubernetes.io/part-of: brobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: brobot
      app.kubernetes.io/part-of: brobot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: brobot
        app.kubernetes.io/part-of: brobot
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: web-pool
      containers:
        - name: "brobot"
          image: gcr.io/tk8-cluster/brobot:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                    name: config
                    key: token
            - name: FIREBASE_64
              valueFrom:
               secretKeyRef:
                   name: config
                   key: firebase
