#!/bin/bash
set -e

WORKSPACE=${1:-dev}

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -o allexport; source "${_scripts}/../.env.base"; set +o allexport

case $WORKSPACE in
  dev)
    set -o allexport; source "${_scripts}/../.env.dev"; set +o allexport
    ;;

  prod)
    set -o allexport; source "${_scripts}/../.env.prod"; set +o allexport
    ;;

  *)
    echo -n "unknown workspace"
    ;;
esac

stage=$WORKSPACE npx tsx src/redeploy.ts
