#!/bin/bash
set -e

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_app="${_scripts}/.."
_terraform="${_app}/infra/terraform"

# import base properties, e.g. APP_NAME
set -o allexport; source "${_app}/.env.base"; set +o allexport
set -o allexport; source "${_app}/.env.prod"; set +o allexport

if [ -z ${APP_NAME+x} ]; then
  echo "Must supply APP_NAME (should be in .env)";
  exit 1
fi

# Terraform state, bucket name
AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r '.Account')
terraform_state_bucket="terraform-remote-$AWS_ACCOUNT_ID"

# Cleanup .terraform
pushd "${_terraform}" >/dev/null
rm -rf .terraform/

# Deploy terraform
terraform init \
  -backend-config bucket="${terraform_state_bucket}" \
  -backend-config="region=${TF_VAR_region:-us-west-2}" \
  -backend-config="key=${APP_NAME}" \
  >/dev/null

terraform_args=()

if [ ! -z ${CI+x} ]; then
  terraform_args+=(-auto-approve)
fi

echo "Deploying"

TF_VAR_cloudflare_api_token=$CLOUDFLARE_API_TOKEN \
TF_VAR_cloudflare_account_id=$CLOUDFLARE_ACCOUNT_ID \
  terraform apply "${terraform_args[@]}"

popd
