#!/usr/bin/env bash

set -e

: "${APP_ID:?Need to set APP_ID non-empty}"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TAG="registry.digitalocean.com/brophylactic-gaming/bro-bot"

DOCKER_BUILDKIT=1 docker build -t $TAG .
docker push $TAG

doctl apps create-deployment $APP_ID --wait