#!/bin/bash
set -e

# import base properties
_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -o allexport; source "${_scripts}/../.env.base"; set +o allexport
set -o allexport; source "${_scripts}/../.env.dev"; set +o allexport

stage="local" npm run start
