#!/bin/bash
set -e

ENV=${1:-dev}

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -o allexport; source "${_scripts}/../.env.base"; set +o allexport
set -o allexport; source "${_scripts}/../.env.${ENV}"; set +o allexport

stage="local" npm run start
