#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TAG="registry.digitalocean.com/brophylactic-gaming/bro-bot"

docker build -t $TAG .
docker push $TAGs
